import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'NextNews',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=optional" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons&display=optional"/>
      </head>
      <body>{children}</body>
    </html>
  )
}
