import { Metadata } from "next"
import ThemeProvider_ from "@/styles/themeProvider"
import TopNav from "./_components/topnav"
import {CountryChangeButton, CountryProvider} from "./_components/btnCountryChange"

export const metadata: Metadata = {
  title: 'NextNews',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=optional" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons&display=optional"/>
      </head>
      <body>
        <ThemeProvider_>
          <CountryProvider>
            
            <TopNav />
            {children}
          </CountryProvider>
        </ThemeProvider_>      
      </body>
    </html>
  )
}
